### ISSUE TITLE
YeoPress isn't installing all of the files

### ISSUE THREAD

**Issue by ryanaltvater** [wesleytodd/YeoPress#159]
I've been using YeoPress for a while and haven't had this issue until recently. During installation, I'm not receiving all of the files. Below is my YeoPress setup and a screenshot of the output.

? WordPress URL: http://192.168.33.10
? Table prefix: wp_
? Database host: localhost
? Database name: scotchbox
? Database user: root
? Database password: root
? Use Git? No
? Would you like to install WordPress with the custom directory structure? No
? Install a custom theme? No
? Does this all look correct? Yes

>> Installing WordPress 4.2.2
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
>> WordPress installed
>> Getting salt keys
>> Writing WP files to disk
>> Setting Permissions: 0755 on .
>> Setting Permissions: 0775 on wp-content
>> Cannot access database
>> Make sure you create the database and update the credentials in the wp-config.php
>> Writing .yeopress file

![screen shot 2015-05-21 at 1 31 21 pm](https://cloud.githubusercontent.com/assets/1336787/7754857/b2923028-ffbd-11e4-8fc8-376fe8061cf2.png)

**Comment by wesleytodd** [comment]
#158 148

**Comment by wesleytodd** [comment]
sorry if you got an email linking to the wrong issue, #148 is the right one

**Comment by ryanaltvater** [comment]
I'm confused as to why I'm being directed to #148. I'm not getting any of those errors and nothing under that issue was helpful at all.

**Comment by wesleytodd** [comment]
That issue is were we finalized the discussion resulting from a series of other issues that were filed.  Sorry, I should have posted a better explanation, I thought it was better explained in that issue, I was wrong.

There are several issues linked to in that thread that describe this exact issue.  All of them were resolved by upgrading the underlying yeoman-generator package, which was resolved during the process of fixing that error.  Updating to the newest generator should fix it for you.

Also, in the future, on an OS project try to search the resolved issues before opening a new one.  There have been like 5 of this exact issue opened.  That was the reason for my short answer in the first place, so sorry if I came across as a being mean.

**Comment by ryanaltvater** [comment]
I've already tried updating all of the packages and that didn't fix it.

**Comment by wesleytodd** [comment]
Hmm, ok.  Can you try running these and pasting the input:

```
npm list -g generator-wordpress
yo --version
```

**Comment by ryanaltvater** [comment]
npm list -g generator-wordpress
/usr/local/lib
└── generator-wordpress@2.0.1 

yo --version
1.4.6

**Comment by wesleytodd** [comment]
Also FWIW, I haven't really gotten any confirmation from any of these people that it resolved their issues: #155 #147 #150 #149 

But this person said updating did the trick: https://github.com/wesleytodd/YeoPress/issues/157#issuecomment-101383405

**Comment by wesleytodd** [comment]
Hmm, looks like you are up to date with me.  @Toddses Have you had any issues with this since our last release?

**Comment by escobar022** [comment]
Did you try the new version? removing it and reinstalling it? clearing the cache for npm  ( rm -rf ~/.cache/* on Mac )

**Comment by ryanaltvater** [comment]
Clearing the cache worked. Thanks @escobar022!

**Comment by escobar022** [comment]
No problem! It seems that the system doesnt know how to clear the cache, wonder why

**Comment by Toddses** [comment]
It just doesn't clear the cache when you update. If a bad file is already cached, you're gonna have a bad time. I'm not sure we should do anything about that. Its basically standard Yeoman behavior.

You can force YeoPress to clear the cache, by using the `--advanced` flag and saying yes to the force remote refresh prompt.

**Comment by wesleytodd** [comment]
Oh, haha, yeah it was the yeoman cache, good call @escobar022, I totally didn't think of that.  Good job team!!!!  Open Source to the rescue!

**Comment by wesleytodd** [comment]
Also, @Toddses I agree that we should not do anything about this.  But I will post a link to this thread if anyone posts any more copies of this issue.

**Comment by wesleytodd** [comment]
I should stop and think before hitting comment.  One more thing...

@escobar022 If you are interested in helping out with the project I am looking for all the contributors I can.  So if you have any features/fixes/documentation you want to contribute I can get you involved.  Also I was thinking I need to add a contributors section to the readme and package.json, so I will do that for sure.

**Comment by escobar022** [comment]
@wesleytodd Absolutely, I have some ideas on cleaning up the install (removing unnecessary templates) etc. Will make a fork and maybe we can discuss

**Comment by wesleytodd** [comment]
@escobar022 Great!! Let me know!

**Comment by keeprock** [comment]
Works for me too! Great one @escobar022 for a cache tip. Scratch my head about this issue for 1 hour straight until finally found that thread.

**Comment by Trebohdz** [comment]
So, I just have to clean the cache like "npm clean cache", later I reinstalled yeoman, but it still the same error

**Comment by Toddses** [comment]
@Trebohdz That is not the correct way to clear the cache for YeoPress / Yeoman. `rm -rf ~/.cache/*` would be the correct command, but you can also run YeoPress with the `--advanced` flag and say yes to the Force Remote Refresh prompt.
